spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

server:
  address: 0.0.0.0