spring:
  datasource:
    username:
    password:
    url: jdbc:postgresql://localhost:5432/postgre
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false